wp:
  - {x: 2.0, y: 0.6, z: 0.0, yaw: 0}
  - {x: 3.1, y: -0.8, z: 0.0, yaw: 0}
  - {x: 3.6, y: -2.4, z: 0.0, yaw: 0}
  # - {x: -1.2, y: -1.2, z: 0.0, yaw: 0}
  # - {x: -6.5, y: -1.0, z: 0.0, yaw: 0}
  # - {x: 3.0, y: 2.0, z: 0.0, yaw: 0}
  # - {x: 3.0, y: -2.5, z: 0.0, yaw: 0}
  # - {x: -10.0, y: 2.0, z: 0.0, yaw: 0}
  # - {x: 3.5, y: -0.5, z: 0.0, yaw: 0}